### ISSUE TITLE
规则转换在转换某些脚本的时候异常

### ISSUE THREAD

**Issue by Leowolf93** [chengkongyiban/Surge#4]
您好，我使用了 surge 的QX重写&规则集转化模块，在转换此quantumult x conf 的时候，出现了连接不能访问的情况。
conf 地址:https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/Weibo.conf
https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/StartUp.conf
具体表现为访问此链接的时候一直是活跃（未响应）和错误状态:https://api.weibo.cn/2/searchall
十分感谢。

**Comment by chengkongyiban** [comment]
此为旧版本，请更新至最新版本后重试，
以下为新版本链接

https://github.com/Script-Hub-Org/Script-Hub

**Comment by Leowolf93** [comment]
您好，Wiki 界面的图片挂掉了

**Comment by chengkongyiban** [comment]
https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/modules/script-hub.surge.sgmodule

安装上面的模块

http://script.hub

打开上面的网页

将qx重写填入  来源链接

**Comment by chengkongyiban** [comment]
另外微博去广告用下面的

微博  qx重写
https://raw.githubusercontent.com/RuCu6/QuanX/main/Rewrites/Cube/weibo.snippet

微博国际版  Surge模块
https://raw.githubusercontent.com/Keywos/rule/main/module/weibous.sgmodule

**Comment by Leowolf93** [comment]
您好，我按照您说的步骤，将 https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/Weibo.conf 拷贝至来源链接，来源类型选择了 QX 重写，目标类型选择了 Surge 模块，但是依旧不能使用，您推荐的那个微博 qx 重写也是一样，一旦转换后，微博的发现页无限转圈。
![IMG_0382](https://github.com/chengkongyiban/Surge/assets/115647782/a983bcde-0e66-4ed9-86f3-027bef7edfc6)

**Comment by chengkongyiban** [comment]
来电报群反馈吧
https://t.me/zhangpeifu

**Comment by chengkongyiban** [comment]
此为微博HTTP/2服务器不标准的问题 Surge在 2998版本对其进行了兼容

https://t.me/SURGEPRO/1295998
